version: '3.8'

services:
  plumise-oracle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plumise-oracle
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
